name: OR Condition DEMO
on:
  push:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run only certain users
        if: github.actor == 'tribikram'
        run: echo "Triggered By Tribikram D"
      - name: Run if user is not Tri
        if: github.actor != 'tribikram1'
        run: echo "Running this bacause campare was with tribikram1"
